version: '3.0'

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  apidemon:
    container_name: apidemon
    build: ./apidemon
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./apidemon:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: always

  request_handler:
    build: request_handler/
    ports:
      - 1234:1234