apiVersion: v1
kind: Secret
metadata:
  name: fastapi-server-credentials
  namespace: default
data:
  database_url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLWRiLXNlcnZpY2U6NTQzMi9sb2NhbGJvYXJk
