apiVersion: v1
kind: Secret
metadata:
  name: tgbot-client-credentials
  namespace: default
data:
  token: NTQ2ODQ5MjM1MTpBQUZ3ejRrRFNTWGhHRFdJeGNmT3NzT0dEdGYxTmRhMndDUQ==
  apidemon_url: aHR0cDovL2Zhc3RhcGktc2VydmVyLXNlcnZpY2U6ODAwMA==
