"""migration db

Revision ID: 357a100080ee
Revises: 5952899d9c1b
Create Date: 2023-02-28 18:20:21.354725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357a100080ee'
down_revision = '5952899d9c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
