"""migration

Revision ID: 3ceb03a4a09d
Revises: 460359da7a89
Create Date: 2023-02-02 12:11:24.935340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ceb03a4a09d'
down_revision = '460359da7a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_offer_offer_id'), 'offer', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_photo_offer_photo_id'), 'offer_photo', ['offer_photo_id'], unique=False)
    op.create_index(op.f('ix_request_request_id'), 'request', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_log_request_log_id'), 'request_log', ['request_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_log_request_log_id'), table_name='request_log')
    op.drop_index(op.f('ix_request_request_id'), table_name='request')
    op.drop_index(op.f('ix_offer_photo_offer_photo_id'), table_name='offer_photo')
    op.drop_index(op.f('ix_offer_offer_id'), table_name='offer')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    # ### end Alembic commands ###
