"""migration

Revision ID: b297465ca512
Revises: b694279c7096
Create Date: 2023-02-22 22:34:37.149533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b297465ca512'
down_revision = 'b694279c7096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_index('ix_user_chat_id', table_name='user')
    op.create_unique_constraint(None, 'user', ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_chat_id', 'user', ['chat_id'], unique=False)
    op.drop_column('offer', 'quantity')
    # ### end Alembic commands ###
