"""migration

Revision ID: b694279c7096
Revises: 
Create Date: 2023-02-06 20:24:50.396203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b694279c7096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_chat_id'), 'user', ['chat_id'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('busy', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_chat_id'), 'groups', ['chat_id'], unique=True)
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_table('offer',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_offer_offer_id'), 'offer', ['offer_id'], unique=False)
    op.create_table('request_log',
    sa.Column('request_log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('request_log_id')
    )
    op.create_index(op.f('ix_request_log_request_log_id'), 'request_log', ['request_log_id'], unique=False)
    op.create_table('offer_photo',
    sa.Column('offer_photo_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.offer_id'], ),
    sa.PrimaryKeyConstraint('offer_photo_id'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_index(op.f('ix_offer_photo_offer_photo_id'), 'offer_photo', ['offer_photo_id'], unique=False)
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.offer_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_request_request_id'), 'request', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_user_id'), 'request', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_user_id'), table_name='request')
    op.drop_index(op.f('ix_request_request_id'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_offer_photo_offer_photo_id'), table_name='offer_photo')
    op.drop_table('offer_photo')
    op.drop_index(op.f('ix_request_log_request_log_id'), table_name='request_log')
    op.drop_table('request_log')
    op.drop_index(op.f('ix_offer_offer_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_chat_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_chat_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
