"""migration db

Revision ID: e1efc20ec1c0
Revises: d507e5bd025b
Create Date: 2023-03-02 14:56:11.561818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1efc20ec1c0'
down_revision = 'd507e5bd025b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('photo', sa.String(), nullable=True))
    op.drop_column('offer', 'phoro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('phoro', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('offer', 'photo')
    # ### end Alembic commands ###
